### PR TITLE
Add 10X processing mode.

### PR DESCRIPTION
**Pull request by keiranmraine**
@drjsanger can you confirm that you are happy for the x10 stuff to be added in.

### CODE REVIEW

**Comment by drjsanger** [comment]
@constantAmateur had suggested he may be able to come up with some test cases for this.

**Comment by keiranmraine** [comment]
If @constantAmateur can give a time line we can decide if this can go in this release.  Likely it's not needed until early next week as I need to complete the WXS docker images still.

**Comment by constantAmateur** [comment]
@keiranmraine @drjdev I should be able to have add a simple test of the 10X processing mode by the end of this week, early next week at the latest.

**Comment by constantAmateur** [comment]
@drjsanger @keiranmraine I've added a basic test of the 10X processing mode.

**Pull request merged**
